---
- hosts: all
  vars:
     dsm_agent_download_hostname: app.deepsecurity.trendmicro.com
     dsm_agent_download_port: 443
     dsa_activation_hostname: agents.deepsecurity.trendmicro.com
     dsa_activation_port: 443
     tenant_id: 111A111A-1A1A-11AA-AAA-11AA11111111
     tenant_password: 111A111A-1A1A-11AA-AAA-11AA11111111
     default_policy_id: 1
  tasks:
    - name: Configure the playbook for the current distribution
      include_vars: '{{ item }}'
      with_first_found:
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version|truncate(2) }}.yml"
        - "vars/default.yml"

    - name: Update user
      debug: msg="Selected agent is {{ ansible_distribution }}-{{ ansible_distribution_major_version|truncate(2) }}"

    - name: Update user
      debug: msg="Downloading agent from https://{{ dsm_agent_download_hostname }}:{{ dsm_agent_download_port }}/{{ agent_relative_path }}/{{ ansible_architecture }}/"

    - name: Download the Deep Security agent
      get_url: url="https://{{ dsm_agent_download_hostname }}:{{ dsm_agent_download_port }}/{{ agent_relative_path }}/{{ ansible_architecture }}/" dest="{{ agent_local_path }}" validate_certs=no

    - name: Install the Deep Security agent
      yum: name={{ agent_local_path }} state=installed update_cache=true
      when: ansible_pkg_mgr == "yum"

    - name: Install the Deep Security agent
      apt: deb={{ agent_local_path }} state=present update_cache=true
      when: ansible_pkg_mgr == "apt"

    - name: Install the Deep Security agent
      zypper: name={{ agent_local_path }} state=present update_cache=true
      when: ansible_pkg_mgr == "zypper"

    - name: Reset the Deep Security agent
      command: /opt/ds_agent/dsa_control -r

    - name: Activate the Deep Security agent
      command: /opt/ds_agent/dsa_control -a dsm://{{ dsa_activation_hostname }}:{{ dsa_activation_port }}/ "tenantID:{{ tenant_id }}" "tenantPassword:{{ tenant_password }}"